apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ydfvu9s0a-java-quarkus
  janus-idp.io/tekton: ydfvu9s0a-java-quarkus
  backstage.io/kubernetes-id: ydfvu9s0a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ydfvu9s0a-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
